apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - artifacts-pvc.yaml
  - surrealdb.yaml
  - backend.yaml
  - frontend.yaml
  - judge.yaml
  - ingress/backend.yaml
  - ingress/frontend.yaml
  - ingress/judge.yaml
